### PR TITLE
Switch to using xargo rather than cargo for building Zinc.

### PR DESCRIPTION
**Pull request by brandonedens**
Use xargo to build libcore and Zinc:
cargo install xargo
xargo build --target thumbv7m-none-eabi

### CODE REVIEW

**Comment by farcaller** [comment]
You need to update support/build-jenkins.sh to call in xargo (and to install it).

**Comment by brandonedens** [comment]
Sorry for the delay. Hopefully I updated the support script correctly.

**Comment by farcaller** [comment]
Apparently travis image doesn't come with rustup 😞: https://travis-ci.org/hackndev/zinc/jobs/172830505#L386

**Comment by dhylands** [comment]
Here's one way of doing it:
https://github.com/fabricedesre/cc3200-rs/blob/master/.travis.yml
https://github.com/fabricedesre/cc3200-rs/blob/master/scripts/travis.sh

**Comment by mcoffin** [comment]
I had to add back in the `rlibc` dependency, but with `xargo` we can now at least use the version from crates.io unmodified!

This is because LLVM, especially in debug mode, likes to render references to `memcpy` and friends, assuming that you'll provide an implementation.

**Comment by mcoffin** [comment]
As of https://travis-ci.org/hackndev/zinc/jobs/177109695 all the cross-platforms build. One of the `kcov` tasks (the platformtree one) is now failing for the `native` target. I'll have to take a look later, but we're close.

**Comment by mcoffin** [comment]
@brandonedens I should be able to pull this with [https://www.traviscistatus.com](travis comes back up). I fixed the problem and it's working locally. For some reason, the downloaded version of `rustup` isn't setting the path for the core system libraries properly, so when the binaries are run with `kcov` you have to set `LD_LIBRARY_PATH` manually for it to be able to find things like `libcore`, `libsyntax`, etc.

**Comment by farcaller** [comment]
"native" seems to start being broken "by design" 😐

**Comment by mcoffin** [comment]
> "native" seems to start being broken "by design"

True, but it's kind of necessary for unit testing... I think it's worth keeping around. Honestly, the problem I'm having with travis now is purely due to differences in the rustup that I'm using locally, and the one travis is using, combined with the lack of a good way to set up an environment identical to the one travis has for testing purposes.

It's going to work very soon here, and trust me, this `xargo` thing is the right way to go right now. It gets rid of all these upstream changes we keep having to track. It will completely deprecate the hackndev fork of `rlibc`, allowing direct use of the version from [crates.io](https://crates.io).

**Pull request merged**
