### PR TITLE
Basic svd to ioregs generator

### PR DESCRIPTION
**Pull request by farcaller**
Supports all the things I could find in LPC svd files. Reference file and output: https://gist.github.com/farcaller/a2fd554c00c102cf9142.

Please try running it over any svd of the platform you have knowledge of and do some verification.

### CODE REVIEW

**Comment by farcaller** [comment]
ruby requiresments: `nokogiri` and `erubis` gems (available via `gem install`). Works with any rustc nightly :wink:

**Comment by 0xc0170** [comment]
I can see that travis fails, same error I have been seeing last 3 days..

I'll look at this, good that it works with any rustc :+1:

**Comment by posborne** [comment]
@farcaller, I am looking at using this as part of my work to add support for the KLxx MCUs.  I started playing with it last night and it generally seems to work (with changes to support the portions of the SVD schema that freescale uses).

Where do you think it makes sense to maintain the SVD conversion stuff.  In Zinc itself (e.g. under support as in here)?  I think that could work as long as we document it and its use (probably include Gemfile as well).  Thoughts?

**Comment by farcaller** [comment]
I think it fits fine under `support/` so far, if ti grows too big we can always fork it off to a dedicated repo.

I'll look into the currently pending changes for svd I have in working tree and will get this PR up to date.

**Comment by posborne** [comment]
@farcaller, thanks, sounds good.  I base my changes off that and publish once its in a working state.

**Comment by farcaller** [comment]
I have some motivation to refactor this quickly into python/lxml/jinja to make code more readable (my ruby code is really quite a mess) but I don't want to bother much really. Do you have any opinion on that, @posborne?

**Comment by posborne** [comment]
@farcaller, Python is fine by me (I have much more experience with it personally) but I don't see a really strong reason to migrate.  If we did migrate to Python as the scripting language of choice for Zinc stuff (all Linux/Mac people probably already  have it installed), I think it might make sense to think about avoiding non-stdlib dependencies.  This just makes it easier to run the scripts without having to worry about setting up a virtualenv, installing dependencies, etc.

For the SVD ioregs generator, this would mean using `xml.etree` and not using Jinja.

**Comment by farcaller** [comment]
Well, I was thinking among the lines of packages that are available in ubuntu repo :smile: there's already 0.6% of such python in repo.

I guess let's leave it as is and rewrite it later if the code becomes really unmanageable.

**Comment by posborne** [comment]
As an FYI, here's the base code generated for the KL25Z.  Unfortunately, the SVD provides very nice descriptions but very bad names (e.g. 0/1) which results in somewhat less than ergonomic results.  I'm going to see if I can think of  something creative for generating names based on the description, but it might be something that requires a human's touch to get right (names are hard).

https://gist.github.com/posborne/2549a1a3c598b66b7ef2

**Comment by posborne** [comment]
Hmmm, many of the field enums also seem 100% incorrect as well: https://gist.github.com/posborne/2549a1a3c598b66b7ef2#file-kl25z_reg-rs-L4311.  I think I just need to change the code to interpret values like `#11` as being binary (So, 0x03) and things should be closer.

**Comment by kblomqvist** [comment]
As a second FYI here's yet another tool for this problem https://github.com/kblomqvist/yasha :D There's even an example in README how to use @posborne's SVD parser within the tool (yasha).

**Pull request merged**
