### PR TITLE
Minimize use of DUMMY_SP

### LINKED ISSUE #99: Minimize the use of DUMMY_SP
Error messages from PT are not that useful as most of them is based on DUMMY_SP.
- [ ] figure out how to provide spans for generated code
- [ ] clean up most (all?) of the `DUMMP_SP` uses

### PR DESCRIPTION
**Pull request by mcoffin**
Makes more meaningful feedback from macro builders.

Fixes  (for ioreg, not for platformtree) #99

### CODE REVIEW

**Comment by farcaller** [comment]
We should have a lint warning for `DUMMY_SP` and `unwrap()` really.

**Comment by mcoffin** [comment]
While DUMMY_SP is pretty specific to compiler plugins (and I suspect it might be removed). I'll probably whip up an external lint plugin to check for unwrap().

**Comment by mcoffin** [comment]
@farcaller FYI
https://github.com/mcoffin/syntaxext_lint

Before this gets merged, I'll publish the dependency crate to crates.io and we can avoid depending on my version from github.

**Comment by farcaller** [comment]
:clap:

**Comment by mcoffin** [comment]
Slightly changing the scope of this PR to only minimize DUMMY_SP for `ioreg` since platformtree might be coming up on a rework.

**Comment by mcoffin** [comment]
r?

**Comment by farcaller** [comment]
ok to test

**Comment by mcoffin** [comment]
I can't see what went wrong with the jenkins build as it's behind a login screen. Probably just doesn't have the build script from the other branch?

**Comment by farcaller** [comment]
Exactly, didn’t have enough time to squash and merge, will do that in an hour is so. Then it just needs to be rebased.

**Comment by farcaller** [comment]
Okay, this can be rebased on master now.

**Comment by mcoffin** [comment]
Just got around to rebasing this as I'm pretty busy with finals through the end of the week. Opened #313 because of issues with the jenkins script.

**Comment by farcaller** [comment]
retest this please

**Comment by farcaller** [comment]
:+1:

**Pull request merged**
