### PR TITLE
svd: updates to svd generator to support Freescale MCUs

### PR DESCRIPTION
**Pull request by posborne**
These changes introduce support for the SVD XML provided by Freescale
for their MCUs.  Changes that were required here were similar to those
that others have had to make for projects like EmbSysRegView
(http://mcuoneclipse.com/2014/05/29/how-to-add-register-details-view-in-eclipse/).

Unfortunately, Freescale's SVD files do not include useful names for
enumerated values for fields, so the generated files will still need
to be modified by maintainers to have useful names.

A couple of changes in here are just cosmetic updates to how the
output looks.

### CODE REVIEW

**Comment by farcaller** [comment]
ok to test

**Comment by farcaller** [comment]
I think we need a test pass to verify that other svd files remain stable, given that it actually makes sense to bundle them in tree (I had to modify LPC's svd file to make it work and look reasonably good as well).

**Comment by farcaller** [comment]
:+1:

**Comment by posborne** [comment]
As an FYI, I started work on a Python version of the SVD generator last night.  I'll open up a PR with that if it works out.  That would have tests and such so we could maintain compatability with the various forms of SVD we are like to encounter over time: https://github.com/posborne/zinc/commit/3aca5284a6b193785480938599256ebce253fd08

**Comment by farcaller** [comment]
SGTM

**Comment by mcoffin** [comment]
@posborne for what it's worth, I found [this](https://github.com/kevinmehall/rust-svd) which would allow for putting the generator in the build script (you'd probably have to change quite a bit of it I imagine).

**Comment by posborne** [comment]
@mcoffin, yeah, I looked at that a bit.  I'm not sure how necessary or wise integrating the SVD transformation into the toolchain is.  That, and rust is maybe not the best tool for doing transformations on XML (though certainly capable).

Right now, I am considering breaking the SVD parser and "library" of SVD XML fragments (I need to look at the license info for each vendor to see if this is OK) into its own repo as that could be useful outside of the zinc ecosystem.  The transformations on the SVD Object Model for zinc would live with the project then.

As of last night, I have a working code generator for Freescale (need to test/support LPC still): https://github.com/hackndev/zinc/compare/master...posborne:svd-generator-python.  Example output (using really rough heuristic to try to fill in for Freescale not providing real "names" for enum values): https://gist.github.com/posborne/757eb9562759ab11dfa8.  It still won't quite compile without some more tweaks.  And you get fun enumerated values like `LOGIC_LEVEL_1_IS_DRIVEN_ON_PIN_PROVIDED_PIN_IS_CONFIGURED_FOR_GENERAL_PURPOSE_OUTPUT`.  I mean, it's better than `E_1`, but it also isn't good.

**Pull request merged**
