### PR TITLE
Nightly churn

### PR DESCRIPTION
**Pull request by bgamari**
So... much... breakage....

### CODE REVIEW

**Comment by bgamari** [comment]
This incorporates @0xc0170's work from #265.

**Comment by 0xc0170** [comment]
Thanks, I have been waiting for that PR to be merged so we can start fixing again recent breaking changes which were quite few of them as we can see.

I'll close my PR

**Comment by bharrisau** [comment]
Sorry, out of communications over Christmas break.

**Comment by farcaller** [comment]
We still need https://github.com/bharrisau/rust-librlibc/pull/1 to land this, right?

**Comment by 0xc0170** [comment]
@farcaller Yes.

@bharrisau Please can you look at PR in your repo - rlibc?

**Comment by bharrisau** [comment]
Done.

**Comment by farcaller** [comment]
```
/home/travis/build/hackndev/zinc/src/platformtree/builder/mod.rs:99:27: 99:38 error: type `core::cell::RefMut<'_, collections::vec::Vec<alloc::rc::Weak<node::Node>>>` does not implement any method in scope named `deref_mut`
/home/travis/build/hackndev/zinc/src/platformtree/builder/mod.rs:99       let deps = sub_deps.deref_mut();
                                                                                              ^~~~~~~~~~~
```

`deref_mut` is now allowed only implicitly, as a `*v` operation on `mut v`.

**Comment by bgamari** [comment]
@farcaller, sleep got the best of me before I could finish the set. Now I'm restless and so here's the rest ;)

**Comment by bgamari** [comment]
Alright, we have green.

**Comment by farcaller** [comment]
LGTM, thanks a lot for your work!

**Pull request merged**
