### PR TITLE
Fix building with recent nightly (after commit f5a99ae).

### PR DESCRIPTION
**Pull request by hugwijst**

### CODE REVIEW

**Comment by farcaller** [comment]
Thanks!

**Comment by mcoffin** [comment]
I've updated `syntaxext_lint` upstream. Re-running the travis build on master.

**Comment by mcoffin** [comment]
See new build info [here](https://travis-ci.org/hackndev/zinc/builds/81458608) (only `native` build still failing).

**Comment by farcaller** [comment]
Yup, native is a bit broken for a few weeks now, should get back to fixing it :hourglass_flowing_sand:

**Pull request merged**
