### PR TITLE
Added kcov coverage for travis/coveralls

### PR DESCRIPTION
**Pull request by farcaller**

### CODE REVIEW

**Comment by mcoffin** [comment]
It would be nice to have the badge added to the README along with this.

**Comment by farcaller** [comment]
It's currently broken, as it needs kcov binary from HEAD and the paths are src/ relative anyway.

**Comment by farcaller** [comment]
Okay, I have no idea how to make coveralls work properly, OTOH jenkins parses the kcov report quite fine

**Comment by posborne** [comment]
Something following might work (haven't tested on travis), if we really want kcov upstream now:

```sh
sudo apt-get build-dep kcov
wget https://github.com/SimonKagstrom/kcov/archive/v27.tar.gz
tar xzvf v27.tar.gz
mkdir kcov-27/build
cd kcov-27/build
cmake ..
make
sudo make install
```

**Comment by farcaller** [comment]
kcov has a bunch of weird deps and still doesn't work with coveralls so far as json format changed.

**Comment by posborne** [comment]
> kcov has a bunch of weird deps and still doesn't work with coveralls so far as json format changed.

Gotcha.  The above worked for me on a 14.04 machine (travis is 12.04 I think) but who knows if I installed something earlier.  None of that matters if coveralls still won't understand the output.

**Comment by farcaller** [comment]
Works for at least jenkins now.

**Comment by SimonKagstrom** [comment]
@posborne A fair amount of rust projects clone kcov to run the coveralls tests, basically with the method you propose. See for example:

https://github.com/maidsafe/maidsafe_client/blob/master/.travis.yml

I think apt-get build-deps kcov can cause problems since the kcov in Ubuntu 12.04 (and I think 14.04) is quite old and is likely missing some dependencies.

**Pull request merged**
